/**
 * @Author: ironman
 * @Date:   2021-05-26T08:35:01-04:00
 * @Last modified by:   ironman
 * @Last modified time: 2021-05-28T04:54:38-04:00
 */



/*we generated guess game in whiCH we generated random number and make some condition  */
#include<stdio.h>
#include<stdlib.h>
#include<time.h>

int main () {
    int number , guess , attempt = 1;
    srand (time(NULL));
    number = rand()%20 + 1;

        //  printf ("***** RANDOM NUMBER GENERATED BY PROGRAM IS ***** : \n******(%d)****** " , number);;
        /* Generating random number has completed */
        //Now instruction for further task to make a guessing game are progammed below ;

    do
    {
        //message for user
        printf ("Guess the random number generated by program  (1-20)\n ");
        //asking guess number from user
        scanf ("%d",&guess);
        // showing user there guess number
        printf("\n\nYou guessed --%d--\n",guess);
        //for showing
        printf("\nChecking database.......\n");

            //writting condition for cheking
            if (guess < number)
            {
                    printf ("\n ***higher number please \n");
            }
            //same condition and msg to apppear
            else if (guess > number)
            {
                    printf ("\n *** Lower Number Please \n");
            }
            //if upper condition didn't match then this below one get executed
            else
            {
                    //message to appear if information get correct
                    printf ("Huurray! You have guessed the correct number\n");
                    //showing the random number generated by code
                    printf ("\n***** RANDOM NUMBER GENERATED BY PROGRAM WAS ***** : --- %d ---" , number);
                    //message
                    printf ("\nYou have guesed the number in --- %d --- attempt \n congrats once again from ironman !@# \n\n\n " ,attempt);
                    /* as all upper 3 print instruction will only be printed if we get correct guess
                    and then if we don't apply break then we will be asked to  enter the guess number
                    again because loop remain opened though in this condition so we apply break if this
                    else get executed then loop get closed because in our condition these statement
                    will only print if guess is write and we just want that*/
                    break ;

            }
                    //we have puuted attempt variable and each time the loop repeat value of attempt get incr
                    //ese and we get the number that how much time this loop run and we can declare
                    // the attempt tried by user and even can print like we have done in upper statement
                    attempt++;
    // this below condtion describe us that if the guess number of user din't match with number prouced by
    //program the loop remain continued
    }while(guess!=number);
    return 0 ;

}
