			/*WHERE Clause */
SELECT *FROM employees WHERE EMPLOYEE_ID = 3 ;

			/*Logical Operator */
SELECT *FROM employees WHERE LAST_NAME = 'Demon' AND SALARY = 1500 ;
SELECT *FROM employees WHERE FIRST_NAME = 'Demon' OR SALARY = 1500 ;
SELECT *FROM employees WHERE  NOT SALARY = 2000 ;
			
            /*Comparision Operator*/
SELECT *FROM employees WHERE SALARY > 1000 ;
SELECT *FROM employees WHERE SALARY >= 1000 ;
SELECT *FROM employees WHERE SALARY != 1000 ;
SELECT *FROM employees WHERE SALARY <> 2000 ;

				/*Special Operator*/
SELECT *FROM employees WHERE SALARY BETWEEN 1500 AND 2500 ;
SELECT *FROM employees WHERE FIRST_NAME LIKE 'mad';
SELECT *FROM employees WHERE FIRST_NAME LIKE 'm%';
SELECT *FROM employees WHERE SALARY IS NULL;
SELECT *FROM employees WHERE SALARY IN (1000 ,1200,1700,1500);
SELECT DISTINCT (SALARY) FROM employees;

		  /*Aggregation Function*/
SELECT COUNT(*) FROM employees ;
SELECT MAX(SALARY) FROM employees ;
SELECT MIN(SALARY) FROM employees ;
SELECT AVG(SALARY) FROM employees ;

			  /*ADDING COLUMNS*/
ALTER TABLE employees ADD COLUMN DEPARTMENT_ID INT ;			
ALTER TABLE employees ADD COLUMN DEPT VARCHAR(10);

		  /*UPDATING TABLE DATAS IN NEW COLUMN*/
UPDATE employees SET DEPARTMENT_ID = '101' , DEPT = 'SALES' WHERE EMPLOYEE_ID=2; 
UPDATE employees SET DEPARTMENT_ID = '102' , DEPT = 'GOPNIYA' WHERE EMPLOYEE_ID=3; 
UPDATE employees SET DEPARTMENT_ID = '103' , DEPT = 'ADMIN' WHERE EMPLOYEE_ID=4; 
UPDATE employees SET DEPARTMENT_ID = '102' , DEPT = 'GOPNIYA' WHERE EMPLOYEE_ID=6; 

		  /*GROUP BY CLAUSE*/
SELECT FIRST_NAME,MAX(SALARY),DEPARTMENT_ID,DEPT FROM employees GROUP BY DEPT ;
SELECT AVG(SALARY),DEPT FROM employees GROUP BY DEPT ;

		/*HAVING CLAUSE*/
SELECT AVG(SALARY),DEPT FROM employees GROUP BY DEPARTMENT_ID HAVING COUNT(DEPARTMENT_ID)>=2;
SELECT FIRST_NAME,MAX(SALARY),DEPT FROM employees GROUP BY DEPARTMENT_ID HAVING COUNT(DEPARTMENT_ID)>=2;

		/*ORDER BY Clause*/
SELECT *FROM employees ORDER BY SALARY ;
SELECT *FROM employees ORDER BY SALARY DESC ;








