CREATE TABLE DEPARTMENT  (
DEPT_ID INT ,
DEPT VARCHAR (20),
DEPT_LOC VARCHAR (20),
PRIMARY KEY (DEPT_ID)
);

INSERT INTO DEPARTMENT VALUES (1,'CONTENT' , 'CHICAGO');
INSERT INTO DEPARTMENT VALUES (2,'SUPPORT' , 'NEW JERSEY');
INSERT INTO DEPARTMENT VALUES (3,'SALES' , 'BOSTON');
INSERT INTO DEPARTMENT VALUES (4,'HR' , 'CHICAGO');
INSERT INTO DEPARTMENT VALUES (5,'OPERATIONS' , 'NEW YORK');

SELECT *FROM DEPARTMENT ;
SELECT *FROM employees ;

	/*INNER JOIN*/
SELECT e.FIRST_NAME , e.SALARY ,d.DEPT,d.DEPT_LOC
FROM employees e
INNER JOIN DEPARTMENT d 
on e.DEPT = d.DEPT ;

	/*LEFT JOIN*/
SELECT e.FIRST_NAME , e.SALARY ,e.DEPARTMENT_ID, d.DEPT,d.DEPT_LOC
FROM employees e 
LEFT JOIN DEPARTMENT d 
ON e.DEPT = d.DEPT ;

	/*RIGHT JOIN*/
SELECT e.FIRST_NAME , e.SALARY ,e.DEPARTMENT_ID, d.DEPT,d.DEPT_LOC
FROM employees e 
RIGHT JOIN DEPARTMENT d 
ON e.DEPT = d.DEPT ;

	/*FULL OUTER JOIN*/
SELECT e.FIRST_NAME , e.LAST_NAME , e.SALARY , d.DEPT_ID , d.DEPT_LOC , d.DEPT 
FROM employees e 
LEFT JOIN DEPARTMENT d 
ON e.DEPT = d.DEPT 
UNION
SELECT e.FIRST_NAME , e.LAST_NAME , e.SALARY , d.DEPT_ID , d.DEPT_LOC , d.DEPT 
FROM employees e 
RIGHT JOIN DEPARTMENT d 
ON e.DEPT = d.DEPT ;

	/*CROSS JOIN*/
SELECT *FROM employees CROSS JOIN DEPARTMENT ;




